# Generated by Django 4.0.4 on 2022-05-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=255, verbose_name='ID транзакции')),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Описание')),
            ],
        ),
    ]
